// apps/examples/components/autosuggest/vue/vue-create-vue/src/App.vue
<script setup>
import Autosuggest from "./components/Autosuggest.vue";
</script>

<template>
  <main>
    <h2>what3words Autosuggest Component - Vue Create-Vue</h2>
    <form method="POST">
      <div className="form-container">
        <Autosuggest></Autosuggest>
      </div>
      <button type="submit" data-testid="submit">Complete</button>
    </form>
  </main>
</template>

<style scoped></style>

// apps/examples/components/autosuggest/react/react-vite/src/App.tsx
import { defineCustomElements } from "@what3words/react-components";

import Autosuggest from "./components/Autosuggest";

import "./App.css";

defineCustomElements(window);

function App() {
  return (
    <>
      <h2>what3words Autosuggest Component - React Vite</h2>
      <form
        method="POST"
        onSubmit={(e) => {
          e.preventDefault();
          console.log({ target: e.target });
        }}
      >
        <div className="form-container">
          <Autosuggest api_key=""></Autosuggest>
        </div>
        <button type="submit" data-testid="submit">
          Complete
        </button>
      </form>
    </>
  );
}

export default App;
